# Индивидуальное задание 1

Создать ноутбук, в котором будут приведены собственные примеры на языке Python для каждого из представленных свойств матричных вычислений.

In [1]:
import numpy as np

Свойство 1. Дважды транспонированная матрица равна исходной матрице:

In [3]:
A = np.matrix('5 7 3; 4 5 6')
print(A)

[[5 7 3]
 [4 5 6]]


In [4]:
R = (A.T).T
print(R)

[[5 7 3]
 [4 5 6]]


Свойство 2. Транспонирование суммы матриц равно сумме транспонированных матриц:

In [5]:
A = np.matrix('1 9 3; 3 2 6')
B = np.matrix('7 4 5; 1 2 5')
L = (A + B).T

print(L)

[[ 8  4]
 [13  4]
 [ 8 11]]


In [6]:
R = A.T + B.T
print(R)

[[ 8  4]
 [13  4]
 [ 8 11]]


Свойство 3. Транспонирование произведения матриц равно произведению транспонированных
матриц расставленных в обратном порядке:

In [8]:
A = np.matrix('1 7; 4 4')
B = np.matrix('8 6; 1 8')
L = (A.dot(B)).T

print(L)

[[15 36]
 [62 56]]


In [9]:
R = (B.T).dot(A.T)
print(R)

[[15 36]
 [62 56]]


Свойство 4. Транспонирование произведения матрицы на число равно произведению этого
числа на транспонированную матрицу:

In [11]:
A = np.matrix('3 5 3; 4 2 6')
k = 3
L = (k * A).T

print(L)

[[ 9 12]
 [15  6]
 [ 9 18]]


In [12]:
R = k * (A.T)
print(R)

[[ 9 12]
 [15  6]
 [ 9 18]]


Свойство 5. Определители исходной и транспонированной матрицы совпадают:

In [13]:
A = np.matrix('1 7; 6 4')
A_det = np.linalg.det(A)

print(format(A_det, '.9g'))

-38


In [14]:
A_T_det = np.linalg.det(A.T)
print(format(A_T_det, '.9g'))

-38


# Действия над матрицами

Свойство 1. Произведение единицы и любой заданной матрицы равно заданной матрице:

In [15]:
A = np.matrix('1 6; 3 9')
L = 1 * A

print(L)

[[1 6]
 [3 9]]


In [16]:
R = A
print(R)

[[1 6]
 [3 9]]


Свойство 2. Произведение нуля и любой матрицы равно нулевой матрице, размерность которой
равна исходной матрицы:# 

In [17]:
A = np.matrix('1 2; 3 4')
Z = np.matrix('0 0; 0 0')
L = 0 * A
R = Z
print(L)

[[0 0]
 [0 0]]


In [18]:
print(R)

[[0 0]
 [0 0]]


Свойство 3. Произведение матрицы на сумму чисел равно сумме произведений матрицы на
каждое из этих чисел:

In [20]:
A = np.matrix('6 8; 3 4')
p = 2
q = 3
L = (p + q) * A
R = p * A + q * A
print(L)

[[30 40]
 [15 20]]


In [21]:
print(R)

[[30 40]
 [15 20]]


Свойство 4. Произведение матрицы на произведение двух чисел равно произведению второго
числа и заданной матрицы, умноженному на первое число:

In [22]:
L = (p * q) * A
R = p * (q * A)
print(L)

[[36 48]
 [18 24]]


In [23]:
print(R)

[[36 48]
 [18 24]]


Свойство 5. Произведение суммы матриц на число равно сумме произведений этих матриц на
заданное число:

In [24]:
A = np.matrix('3 4; 3 4')
B = np.matrix('7 8; 7 8')
k = 3
L = k * (A + B)

print(L)

[[30 36]
 [30 36]]


In [25]:
R = k * A + k * B
print(R)

[[30 36]
 [30 36]]


Умножение матриц

Свойство 1. Ассоциативность умножения. Результат умножения матриц не зависит от порядка, в
котором будет выполняться эта операция:

In [26]:
A = np.matrix('1 1; 2 2')
B = np.matrix('5 5; 6 8')
C = np.matrix('2 1; 1 8')
L = A.dot(B.dot(C))
R = (A.dot(B)).dot(C)
print(L)

[[ 35 115]
 [ 70 230]]


In [27]:
print(R)

[[ 35 115]
 [ 70 230]]


Свойство 2. Дистрибутивность умножения. Произведение матрицы на сумму матриц равно
сумме произведений матриц:

In [28]:
L = A.dot(B + C)
R = A.dot(B) + A.dot(C)
print(L)

[[14 22]
 [28 44]]


In [29]:
print(R)

[[14 22]
 [28 44]]


Свойство 3. Умножение матриц в общем виде не коммутативно. Это означает, что для матриц не
выполняется правило независимости произведения от перестановки множителей:

In [30]:
L = A.dot(B)

print(L)

[[11 13]
 [22 26]]


In [31]:
R = B.dot(A)
print(R)

[[15 15]
 [22 22]]


Свойство 4. Произведение заданной матрицы на единичную равно исходной матрице:

In [32]:
E = np.matrix('1 0; 0 1')
L = E.dot(A)

print(L)

[[1 1]
 [2 2]]


In [33]:
R = A.dot(E)
print(R)

[[1 1]
 [2 2]]


In [34]:
print(A)

[[1 1]
 [2 2]]


Свойство 5. Произведение заданной матрицы на нулевую матрицу равно нулевой матрице:

In [35]:
Z = np.matrix('0 0; 0 0')
L = Z.dot(A)

print(L)

[[0 0]
 [0 0]]


In [36]:
R = A.dot(Z)
print(R)

[[0 0]
 [0 0]]


In [37]:
print(Z)

[[0 0]
 [0 0]]


Свойства определителя матрицы.

Свойство 1. Определитель матрицы остается неизменным при ее транспонировании:

In [38]:
A = np.matrix('-4 2 2; 10 4 -5; 8 -5 1')
print(A)

[[-4  2  2]
 [10  4 -5]
 [ 8 -5  1]]


In [39]:
print(A.T)

[[-4 10  8]
 [ 2  4 -5]
 [ 2 -5  1]]


In [40]:
det_A = round(np.linalg.det(A), 3)
print(det_A)

-180.0


In [41]:
det_A_t = round(np.linalg.det(A.T), 3)
print(det_A_t)

-180.0


Свойство 2. Если у матрицы есть строка или столбец, состоящие из нулей, то определитель
такой матрицы равен нулю:

In [43]:
A = np.matrix('-4 -7 2; 0 0 0; 0 3 1')

np.linalg.det(A)

0.0

Свойство 3. При перестановке строк матрицы знак ее определителя меняется на
противоположный:

In [48]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]


In [49]:
B = np.matrix('10 4 -1; -4 -1 2; 8 3 1')
print(B)

[[10  4 -1]
 [-4 -1  2]
 [ 8  3  1]]


In [50]:
round(np.linalg.det(A), 3)

-14.0

In [51]:
round(np.linalg.det(B), 3)

14.0

Свойство 4. Если у матрицы есть две одинаковые строки, то ее определитель равен нулю:

In [52]:
A = np.matrix('-4 -1 2; -4 -1 2; 8 3 1')
np.linalg.det(A)

0.0

Свойство 5. Если все элементы строки или столбца матрицы умножить на какое-то число, то и
определитель будет умножен на это число:

In [53]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
k = 2
B = A.copy()
B[2, :] = k * B[2, :]
print(B)

[[-4 -1  2]
 [10  4 -1]
 [16  6  2]]


In [54]:
det_A = round(np.linalg.det(A), 3)
det_A * k

-28.0

In [55]:
det_B = round(np.linalg.det(B), 3)
det_B

-28.0

Свойство 6. Если все элементы строки или столбца можно представить как сумму двух
слагаемых, то определитель такой матрицы равен сумме определителей двух соответствующих
матриц:

In [56]:
A = np.matrix('-4 -1 2; -4 -1 2; 8 3 1')
B = np.matrix('-4 -1 2; 8 3 2; 8 3 1')
C = A.copy()
C[1, :] += B[1, :]
print(C)

[[-4 -1  2]
 [ 4  2  4]
 [ 8  3  1]]


In [57]:
print(A)

[[-4 -1  2]
 [-4 -1  2]
 [ 8  3  1]]


In [58]:
print(B)

[[-4 -1  2]
 [ 8  3  2]
 [ 8  3  1]]


In [59]:
round(np.linalg.det(C), 3)

4.0

In [60]:
round(np.linalg.det(A), 3) + round(np.linalg.det(B), 3)

4.0

Свойство 7. Если к элементам одной строки прибавить элементы другой строки, умноженные на
одно и тоже число, то определитель матрицы не изменится:

In [61]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
k = 2
B = A.copy()
B[1, :] = B[1, :] + k * B[0, :]
print(A)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]


In [62]:
print(B)

[[-4 -1  2]
 [ 2  2  3]
 [ 8  3  1]]


In [63]:
round(np.linalg.det(A), 3)

-14.0

In [64]:
round(np.linalg.det(B), 3)

-14.0

Свойство 8. Если строка или столбец матрицы является линейной комбинацией других строк
(столбцов), то определитель такой матрицы равен нулю:

In [65]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
k = 2
A[1, :] = A[0, :] + k * A[2, :]
round(np.linalg.det(A), 3)

0.0

Свойство 9. Если матрица содержит пропорциональные строки, то ее определитель равен нулю:

In [67]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]


In [68]:
k = 2
A[1, :] = k * A[0, :]
print(A)

[[-4 -1  2]
 [-8 -2  4]
 [ 8  3  1]]


In [69]:
round(np.linalg.det(A), 3)

0.0

# Обратная матрица

Свойство 1. Обратная матрица обратной матрицы есть исходная матрица:

In [70]:
A = np.matrix('1. -3.; 2. 5.')
A_inv = np.linalg.inv(A)
A_inv_inv = np.linalg.inv(A_inv)
print(A)

[[ 1. -3.]
 [ 2.  5.]]


In [71]:
print(A_inv_inv)

[[ 1. -3.]
 [ 2.  5.]]


Свойство 2. Обратная матрица транспонированной матрицы равна транспонированной матрице
от обратной матрицы:

In [72]:
A = np.matrix('1. -3.; 2. 5.')
L = np.linalg.inv(A.T)

print(L)

[[ 0.45454545 -0.18181818]
 [ 0.27272727  0.09090909]]


In [73]:
R = (np.linalg.inv(A)).T
print(R)

[[ 0.45454545 -0.18181818]
 [ 0.27272727  0.09090909]]


Свойство 3. Обратная матрица произведения матриц равна произведению обратных матриц:

In [74]:
A = np.matrix('1. -3.; 2. 5.')
B = np.matrix('7. 6.; 1. 8.')
L = np.linalg.inv(A.dot(B))

print(L)

[[ 0.09454545  0.03272727]
 [-0.03454545  0.00727273]]


In [75]:
R = np.linalg.inv(B).dot(np.linalg.inv(A))
print(R)

[[ 0.09454545  0.03272727]
 [-0.03454545  0.00727273]]
