# Индивидуальное задание 2

Создать ноутбук, в котором будут приведены собственные примеры решения систем
линейных уравнений матричным методом и методом Крамера.

# Матричный метод

решение системы линейных алгебраических уравнений по матричному методу определяется равенством

  $$ X = A^{-1} * B $$

В случае, если det A не равен нулю, у системы имеется только один вариант решения: при помощи метода обратной матрицы. Если det A=0, то систему нельзя решить данным методом.

In [2]:
import numpy as np

In [5]:
#Создаем матрицы
A = np.random.randint(-9, 9,(3,3))
B = np.random.randint(-9, 9,(3,1))
print("Первая матрица:\n",A)
print("Вторая матрица:\n",B)

Первая матрица:
 [[-9 -8  4]
 [ 5  1  7]
 [-1  1 -1]]
Вторая матрица:
 [[-8]
 [-7]
 [ 2]]


In [7]:
#Найдем определитель
A_det = np.linalg.det(A)

if round(A_det) != 0: 
    #Найдем обратную и присоединенную матрицу
    A_inv = np.linalg.inv(A)
    R = A_inv.dot(B) 
    i = 1
    for elem in R: 
        print(f"x{i} = {elem}") 
        i += 1
else:
    print("Определитель равен 0, систему решить нельзя!")

x1 = [-0.25]
x2 = [0.8125]
x3 = [-0.9375]


# Метод Крамера

Для решения системы линейных уравнений методом Крамера из коэффициентов при неизвестных составляется главный определитель системы

In [10]:
#Создаем матрицы
A = np.random.randint(-9, 9,(3,3))
B = np.random.randint(-9, 9,(3,1))
print("Первая матрица:\n",A)
print("Вторая матрица:\n",B)

Первая матрица:
 [[ 5 -3  6]
 [-8 -1  3]
 [ 4 -3 -6]]
Вторая матрица:
 [[-5]
 [-1]
 [-8]]


In [11]:
#Найдем определитель
A_det  = np.linalg.det(A)

if round(A_det) != 0:
    #Найдем дополнительные определители
    d_1 = A.copy() 
    d_1 [:, 0] = B[:, 0] 
    x1 = round(np.linalg.det(d_1), 3) / round(A_det, 3)
    
    d_2 = A.copy()  
    d_2[:, 1] = B[:, 0] 
    x2 = round(np.linalg.det(d_2), 3) / round(A_det, 3) 
    
    d_3 = A.copy() 
    d_3[:, 2] = B[:, 0] 
    x3 = round(np.linalg.det(d_3), 3) / round(A_det, 3) 
   
    print("x1:", x1, "\nx2:", x2, "\nx3:", x3)
else:
    print("Матрица вырожденная, нельзя продолжить")

x1: -0.042735042735042736 
x2: 2.1025641025641026 
x3: 0.2535612535612536
